Feature/mapping map to object or array
icapps/ios-faro pull request #71
Opened 2016-09-16 15:30 UTC by doozMen

2016-09-18 07:48 UTC, fousa commented on Example/Example/Model/Model.swift
> +class Model: Parseable {
🍻Woohoo!! Now we can us structs!!

2016-09-18 07:50 UTC, fousa commented on Sources/Service.swift
> +
🖕🏽

2016-09-18 07:50 UTC, fousa commented on Sources/Service.swift
> +                }else {
🖕🏽

2016-09-18 07:53 UTC, fousa commented on Example/Tests/TestHelpers/MockModel.swift
> +    class func extractRootNode(from json: Any) -> JsonNode {
❓I don't get it...

Seems to complicated to me if you have to do this in every model... Maybe we need to look [here](https://github.com/devlucky/Kakapo) to get it fixed.

2016-09-18 07:54 UTC, fousa requested changes

2016-09-19 11:32 UTC, doozMen commented on Example/Tests/TestHelpers/MockModel.swift
> +    class func extractRootNode(from json: Any) -> JsonNode {
Is verhuist naar `Call` nu en dient om het probleem op te lossten

```json
{
"bullshit": {"key":"value"}
"arrayToParse": [...]
}
```

2016-09-19 11:33 UTC, doozMen commented on Sources/Service.swift
> +
Wat is hier uit fout? Ik denk iets met de generics maar vind dat niet terug in onze coding guidelines hoe we dat doen.

2016-09-19 11:39 UTC, fousa commented on Sources/Service.swift
> +
Enter achter de functie definitie 🐜👉🏼👌🏼

2016-09-19 11:40 UTC, fousa commented on Sources/Call.swift
> +    open func rootNode(from json: Any) -> JsonNode {
🍻We love cool naming!

2016-09-19 11:40 UTC, fousa commented on Sources/Call.swift
> +        }else if let json = json as? [String: Any] {
🖕🏽`}else` ➡️ `} else`

2016-09-19 11:40 UTC, fousa commented on Sources/Call.swift
> +        }else {
🖕🏽`}else` ➡️ `} else`

2016-09-19 11:41 UTC, fousa approved these changes

2016-09-19 12:17 UTC, fousa approved these changes

2016-09-19 12:36 UTC, merged