Feature/test serialization
icapps/ios-faro pull request #77
Opened 2016-09-19 16:12 UTC by doozMen

2016-09-19 20:03 UTC, fousa commented on Example/Tests/ParseableSpec.swift
> +        let reations = ["fooRelation": true, "relations": true]
🎈Small typo. `relations`

2016-09-19 20:05 UTC, fousa commented on Sources/Parseable.swift
> +public protocol CustomSerializable {
❓Maybe comment the code with some examples, because I find the function naming a bit to complex.

2016-09-19 20:07 UTC, fousa commented on Example/Tests/ParseableSpec.swift
> +        if key == "fooRelation" {
❓Maybe a small detail, but shouldn't this be a bit less `if`-`else`'y?

2016-09-19 20:08 UTC, fousa requested changes

2016-09-20 06:14 UTC, doozMen commented on Example/Tests/ParseableSpec.swift
> +        let reations = ["fooRelation": true, "relations": true]
#77 anders daar. Zal deze closen

2016-09-20 06:22 UTC, doozMen commented
vervangen door #80

2016-09-20 06:22 UTC, closed without merging