Feature/faro 27
icapps/ios-faro pull request #87
Opened 2016-09-27 13:18 UTC by Periteus

2016-09-27 13:21 UTC, Periteus commented
@doozMen Ik ben nog niet zeker welke logica vanuit Faro en welke in Brutex moet behouden worden

2016-09-27 13:56 UTC, doozMen reviewed
ik fix  wel dat het wat van de logica spreid. Thanks for the effort!

2016-09-28 08:26 UTC, fousa commented on Sources/FaroService.swift
> +            return MockSwitch.shouldMock ? sharedMockService : sharedService
You should be able to set the `MockService` as with a service property no? Wasn't that the purpose in the beginning?

I don't like such if statements...

2016-09-28 08:26 UTC, fousa commented on Sources/FaroService.swift
> +
🖕🏽

2016-09-28 08:26 UTC, fousa commented on Example/Tests/TestHelpers/ApplicationKeys.swift
> +struct ApplicationKeys {
❓Why do we need these `ApplicationKeys` in the tests? Isn't this overkill?

2016-09-28 08:29 UTC, KrisBoonefaes commented on Sources/JSONReader.swift
> +            print(error.localizedDescription)
🖕FaroError pls

2016-09-28 11:32 UTC, doozMen commented on Example/Tests/TestHelpers/ApplicationKeys.swift
> +struct ApplicationKeys {
Will be removed. My mistake.

2016-09-28 11:34 UTC, doozMen commented on Sources/FaroService.swift
> +            return MockSwitch.shouldMock ? sharedMockService : sharedService
I have no other solution. If we have a boolean on Service then we would have an if else in perform

```
perform ...

if mock {
// Load from file
} else {
// Load from service.
}

```

Better?

2016-09-28 11:35 UTC, doozMen requested changes

2016-09-28 11:35 UTC, doozMen commented on Sources/JSONReader.swift
> +            print(FaroError.nonFaroError(error).localizedDescription)
No we have a printError function that you should use

2016-09-28 12:02 UTC, Periteus commented on Sources/JSONReader.swift
> +            print(FaroError.nonFaroError(error).localizedDescription)
Fixed!

2016-09-29 15:27 UTC, doozMen approved these changes

2016-09-29 18:06 UTC, doozMen commented on Sources/FaroService.swift
> +            return MockSwitch.shouldMock ? sharedMockService : sharedService
Ok ik heb het aangepast nu is het een static variabele die je kan zetten.

```
if ApplicationKeys.sharedInstance.shouldMockServices {
            FaroService.sharedService = MockService()
        } else {
            FaroService.setup(with: ApplicationKeys.sharedInstance.baseURL)
        }
if ApplicationKeys.sharedInstance.shouldMockServices {
            FaroService.sharedService = MockService()
        } else {
            FaroService.setup(with: ApplicationKeys.sharedInstance.baseURL)
        }
```
Dat maakt het wat explecieter en gen extra boolean nodig in Faro. Lijkt me ook beter nu. Ok?

2016-09-30 07:06 UTC, merged